const SearchActionsTypes = {
  LAUNCH_SEARCH: 'LAUNCH_SEARCH',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  LOAD_PEOPLE: 'LOAD_PEOPLE',
  LOAD_CHARACTER: 'LOAD_CHARACTER',
  SEARCH_FAILURE: 'SEARCH_FAILURE',
  LOAD_RESPONSE: 'LOAD_RESPONSE',
  LOAD_URL: 'LOAD_URL'
}
export default SearchActionsTypes
